### ISSUE TITLE
Shader has to include "/Engine/Public/Platform.ush" to compile

### ISSUE THREAD

**Issue by elliotstronge** [AyoubKhammassi/CustomComputeShaders#1]
Hey just a heads up I had to add

`#include "/Engine/Public/Platform.ush"`

to the top of the shader in order to get it to compile in UE 4.25. Posting in case anyone else comes across this issue.

**Comment by AyoubKhammassi** [comment]
The project was made in UE 4.24 which didn't require that shader header file. I'll update the Readme file to mention this.
