### ISSUE TITLE
RDG and a structured buffer with an array of custom structs

### ISSUE THREAD

**Issue by ghost** [AyoubKhammassi/CustomComputeShaders#2]
This is not an issue :-) 

I'm trying to learn more about RDG in Unreal and HLSL, so far so good, with one exception: I'm trying to pass an array of a custom struct from C++ to HLSL via a structured buffer, and I currently don't know how to tell the C++ buffer: hey, this is your data so you can pass it to the GPU.

_it is possible that I don't fully comprehend the role and scope of a structured buffer..._

In C++ my shader has
`SHADER_PARAMETER_RDG_BUFFER_UAV(RWStructuredBuffer<FMyStuff>, MyStuffBuffer)`
Then at some point I create it
`FRDGBufferRef MyStuffBuffer = GraphBuilder.CreateBuffer(MyStuffBufferDesc, TEXT("MyStuffBuffer"));`
**here I was expecting to be able to do something like**
`MyStuffBuffer.SetData(some TArray<FMyStuff>)`
then I assign it to the parameters
`PassParameters.MyStuffBuffer = GraphBuilder.CreateUAV(MyStuffBuffer);`
And then I pass everything to the GPU via
`FComputeShaderUtils::AddPass`

I was hoping there is a way, after I create the RDG buffer in C++, to set its data/payload as some `TArray<FMyStuff>` that I previously created and populated in C++

I poked around the source code, but to no avail, this specific aspect of RDG still eludes me 😄 
do you happen to have any idea, by any chance? Thanks!

**Comment by AyoubKhammassi** [comment]
Hey, I'll try to answer your questions with what I know.

> it is possible that I don't fully comprehend the role and scope of a structured buffer...

If you need to pass an array of homogenous data (Your custom struct in this case) to the shader, then structured buffers are the way to go. So you got it right.

> I was hoping there is a way, after I create the RDG buffer in C++, to set its data/payload as some `TArray<FMyStuff>` that I previously created and populated in C++

In Unreal, when creating a new structured buffer (Or any resource for that matter), you need to pass a `FRHIResourceCreateInfo` Struct to the constructor function. That struct contains a `TResourceArray<YouStruct>` that you can fill with whatever data you want your structured buffer to be prepopulated with. Please refer to this [example](https://github.com/AyoubKhammassi/CustomMeshComponent/blob/master/Source/DeformMesh/Private/Components/DeformMeshComponent.cpp#L314-L326)

Now that we got that out of the way, we can talk about RDG resources, these are different from normal resources so don't expect to use them the same way. Their allocation is differed to a later point in time, when the whole dependency graph is completed, optimized, and ready to be executed. So the `FRDGBufferRef` you get from the graph builder is just a handle to a virtual resource that you can use in RDG related stuff, mainly passing it as a pass parameter. 

So if you want a resource to be used as an RDG pass parameter, and you want it to be prepopulated, you'll need to create it differently. there's a method in the graph builder called `GraphBuilder.TryRegisterExternalBuffer()`, but this method only takes `FPooledRDGBuffer` and the reason for that is that the GraphBuilder needs to know for sure that the resource will persist until the moment when the graph will be executed. With normal resources that you create directly through functions like `RHICreateStructuredBuffer()`, you have the ownership and therefore, the graph can't rely on them.
So you can do something like this:
```
//Create a pooled resource
FPooledRDGBuffer* PooledBuffer = new FPooledRDGBuffer();
//Create descriptor 
FRDGBufferDesc Desc = FRDGBufferDesc::CreateStructuredDesc(sizeof(YourStruct), 10);
PooledBuffer->Desc = Desc;
//Create resource array and append the array of your custom struct to it
TResourceArray<YourStruct>* ResourceArray = new TResourceArray<YourStruct>(false);
ResourceArray->Append(YourCPUAarry);

FRHIResourceCreateInfo CreateInfo;
CreateInfo.ResourceArray = ResourceArray;
CreateInfo.DebugName = "DebugName"

//Create the underlying structured buffer owned by the pooled buffer
PooledBuffer->StructuredBuffer = RHICreateStructuredBuffer(Desc.BytesPerElement,
                        Desc.GetTotalNumBytes(),
                        Desc.Usage,
                        CreateInfo);

//Finally, create your RDG Buffer from the Pooled Buffer
FRDGBufferRef MyStuffBuffer = GraphBuilder->TryRegisterExternalBuffer(PooledBuffer);
```

For more information about the RDG, refer to [this presentation](https://epicgames.ent.box.com/s/ul1h44ozs0t2850ug0hrohlzm53kxwrz)

I hope you find this helpful!

**Comment by ghost** [comment]
EDIT: Apparently, this should be enough in 4.26.1 :)

`PassParameters.MyBuffer = GraphBuilder.CreateUAV(CreateStructuredBuffer(GraphBuilder, TEXT("MyBuffer"), sizeof(FMyStruct), MyStructArrayData.Num(), &MyStructArrayData, sizeof(MyStructArrayData)));`
